### ISSUE TITLE
Hit Chance

### ISSUE THREAD

**Issue by Ernesti-CH** [ppach/marrow.github.io#3]
according to the section 3.2.1 the miss chance is:
"Blizzard has confirmed that players have an 8% chance to miss a creature that is 3 levels above them (Blizzard 2019b)."

yet the sources themselves clarify that while the miss chance is 8%, the first 1% hit is ignored by boss mobs (difference defense - attack skill >= 11), making the de-facto miss chance 9% (and thus the hit cap required to achieve with gear).

**Comment by ppach** [comment]
Clarified the wording on that section - added a footnote explaining the different behavior and pointing to the Weapon Skill section.
