### ISSUE TITLE
Hit Chance Formula

### ISSUE THREAD

**Issue by Ernesti-CH** [ppach/marrow.github.io#4]
The Formulae 3.1 and 3.2 have a slight error in them:

if we calculate P(Miss) for 11 or more difference in defense - attack skill, it reads:
0.05 + ((Tlvl *5) - AtkSkill) * 0.2
and for difference 10 or less.
0.05 + ((Tlvl *5) - AtkSkill) * 0.1

however, if we calculate the latter part of the formula for a standard lvl 63 Boss mob and a normal 300 Weapon skill, we get:
(315 - 300) * 0.2 = 3
and then the miss chance should be 8%, so P(Miss) = 5 + 3
instead of "5 + ....", as in "5% + ...." reads 0.05, which is a fractional and does not fit to the percentage calculated in the rest of the formulae

Correctly, they should be written as follows:
5 + ((Tlvl *5) - AtkSkill) * 0.2
5 + ((Tlvl *5) - AtkSkill) * 0.1

**Comment by ppach** [comment]
Fixed. Thank you!
