### ISSUE TITLE
Addition to hit table chart

### ISSUE THREAD

**Issue by lvangh** [ppach/marrow.github.io#5]
(I reached out on Reddit PM but I figure it's easy to miss)

Hello, I saw your guide and wanted to first say great job and we needed something like this for modern WoW. I have been playing on pservers for years (K3) and am continuing on into classic. I have been following the FC and Taladril community for a while. I wanted to know if I could add something I worked in based on MAgey's hit table calculations to your guide. I can reach out on Discord or reply here. It's basically a chart showing the d/w hit table expanded and calculated per level going down from 63 since almost all guides assume L63. I would love to have my chart credited in your guide! I have had it verified by Magey as well for accuracy. Thank you.

I can PM you my Discord #.

**Comment by ppach** [comment]
Hi - I appreciate the willingess to help, but this guide is focused mainly on the raiding aspects. Although I see the why having the calculations for differnt mob levels is beneficial, my aim is to keep the guide concise. 

Regardless, I appreciate your help. Thanks.
