### ISSUE TITLE
Slam formula does not take into account crit and parry multiplier

### ISSUE THREAD

**Issue by Firezi** [ppach/marrow.github.io#6]
Let's look formulas:
![image](https://user-images.githubusercontent.com/18582888/71450606-e5e70180-2775-11ea-89f9-c06e33d541be.png)
Where is `1+p(crit)-p(dodge)` multiplier like in cleave formula?
![image](https://user-images.githubusercontent.com/18582888/71450710-13cd4580-2778-11ea-92f4-6c67199f7f26.png)
Glancing bonus missed too.

**Comment by ppach** [comment]
Hi - these are ommited and stated in a previous footnote. I'll make the wording more clear when I update the guide.

Thanks.
